random_words = [
    "apple", "banana", "cherry", "orange", "grape",
    "python", "programming", "keyboard", "monitor", "mouse",
    "elephant", "zebra", "lion", "tiger", "giraffe",
    "sunflower", "rainbow", "ocean", "mountain", "desert",
    "coffee", "tea", "cake", "cookie", "chocolate",
    "guitar", "piano", "violin", "trumpet", "drums",
    "summer", "winter", "spring", "autumn", "season",
    "book", "novel", "poetry", "story", "chapter",
    "computer", "internet", "software", "hardware", "network",
    "moon", "star", "planet", "galaxy", "universe",
    "camera", "photo", "video", "film", "cinema",
    "bicycle", "car", "train", "bus", "plane",
    "music", "dance", "song", "singer", "artist",
    "pizza", "burger", "pasta", "sushi", "salad",
    "flower", "tree", "grass", "forest", "jungle",
    "friend", "family", "love", "happiness", "smile",
    "color", "painting", "drawing", "sketch", "art",
    "sun", "cloud", "rain", "wind", "weather",
    "pen", "pencil", "notebook", "paper", "writing",
    "candle", "fire", "light", "darkness", "shadow",
    "oxygen", "carbon", "hydrogen", "nitrogen", "element",
    "chemistry", "physics", "biology", "mathematics", "science",
    "oxygen", "carbon", "hydrogen", "nitrogen", "element",
    "chemistry", "physics", "biology", "mathematics", "science",
    "knowledge", "wisdom", "learning", "education", "school",
    "challenge", "goal", "achievement", "success", "victory"
    # Add more words as needed
]